# Generated by Django 3.0.4 on 2020-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='default@gmail.com', max_length=128, verbose_name='이메일 주소'),
            preserve_default=False,
        ),
    ]
